### ISSUE TITLE
Add program dependency section to Anchor.toml

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#106]
Anchor should have a section similar to Cargo's `[dependencies]` section, where one can specify external program dependencies and build them + generate an idl for local development and testing.

To start, this can be a git or local path dependency.

For example,

```toml
[programs]
my-program = { git = "https://github.com/my-org/my-program" }
```

Where the cli will clone the repo, check it's an Anchor workspace, and then traverse the `programs/` dir looking for `my-program` before building and generating an IDL that can be used by the framework.
