### ISSUE TITLE
Build error when adding crate protocol library to anchor project

### ISSUE THREAD

**Issue by gtolarc** [project-serum/anchor#1668]
I created a project with anchor init and added only crate as follows, but it does not build. Can you gays tell me what the problem is?

```toml
[dependencies]
anchor-lang = "0.23.0"
crate-token = { version = "0.5.0", features = ["cpi"] }
```

<img width="1004" alt="error1" src="https://user-images.githubusercontent.com/8623798/159525258-f9ae39bc-fbc3-448e-ac80-328a121e321d.png">
