### ISSUE TITLE
Unable To Provide Multiple Programs To Genesis Test Settings In Anchor.toml

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#207]
At the moment it appears you can only supply at most 1 program like so

```toml
[[test.genesis]]
address = "73YJaFeuh6QxnhPrmXaGNBhFTxvxukw3xY1EzuPZ965k"
program = "./program.so"
```

Attempting to provide more than one as follows results in an error `Unable to start test validator`

```toml
[[test.genesis]]
address = "73YJaFeuh6QxnhPrmXaGNBhFTxvxukw3xY1EzuPZ965k"
program = "./program.so"
[[test.genesis]]
address = "EYEupGvBec2KjMi4mCFzToa3nAhpujFsXKMxX9vbKmQX"
program = "./program_v4.so"
```
