### ISSUE TITLE
anchor test deletes metadata

### ISSUE THREAD

**Issue by hrls** [project-serum/anchor#298]
`metadata` disappears after the test command.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/3259009/119072106-a4529880-b9f3-11eb-8afa-150a97133d20.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/3259009/119072142-b16f8780-b9f3-11eb-8561-2730d4ccf42b.png">

**Comment by armaniferrante** [comment]
The metadata field's behavior is not defined. It's currently used as an implementation detail for testing. 

For the use case above, i.e., testing a previously deployed program, the recommended flow is to add the address to your Anchor.toml.

For example,

```toml
[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[clusters.localnet]
multisig = "F3Uf5F61dmht1xuNNNkk3jnzj82TY56vVjVEhZALRkN"

[clusters.devnet]
multisig = "F3Uf5F61dmht1xuNNNkk3jnzj82TY56vVjVEhZALRkN"

[clusters.mainnet]
multisig = "A9HAbnCwoD6f2NkZobKFf6buJoN9gUVVvX5PoUnDHS6u"
```

Substituting "multisig" and the address with your program name and address.
