### ISSUE TITLE
Enable The Ability To Create Mock Localnet Environments Which Mirror Production Deployments

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#533]
# Overview 

In certain situations you may be developing a program which uses another program. The program which you are integrating does not have information about how to construct its initial state. For example with Raydium there is no information about how to create their lp pools, fusion farms, etc.. In my experience this has meant mocking as much of said program as possible, but this is never perfect and when deploying the program into production the first, there is usually something incorrect due to assumptions made with the mocking process.

# Proposed Solution

The `solana-test-validator` lets you sepcify BPF programs to load, and accounts to clone from mainnet. These two features combined allow you to effectively mirror any production deployment on the localnet.

For example you could have `Anchor.toml` look like

```toml
[[test.genesis]]
address = "abc123"
program = "./foo/bar.so"
[[test.account]]
address = "abc123"
source = "https://some-mainnet-api.com"
```
