### ISSUE TITLE
Enable Solana Test Validator Control Via Anchor.toml

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#534]
# Overview

Occasionally one may want to modify the test validator settings, such as ledger directory, shred count, rpc, etc... At the moment the only way to do this with Anchor is starting the test validator beforehand such that anchor skips creating one.

In addition to this one may want the test validator to stay on after anchor tests finish, perhaps to inspect transactions, or accounts via the cli or connecting the validator to a block explorer.

Additionally one may way to kill the existing validator at the start of the next test run to aovid persisting state in between test runs

# Solution

A proposed solution could be

```toml
[[test.validator]]
terminate-validator-post-test = false
terminate-validator-pre-test = true
limit-ledger-size = 50000000000
url = "https://some-rpc-url.com"
rpc-port = 8899
```
