### ISSUE TITLE
anchor_client: allow custom websocket url for Cluster

### ISSUE THREAD

**Issue by lithdew** [project-serum/anchor#673]
A small proposal for allowing both a custom HTTP JSON-RPC URL and a Websocket URL to be specified in Anchor.toml.

An example of how it may be specified:

```toml
[provider]
cluster = { custom = ["https://api.devnet.solana.com", "ws://api.devnet.solana.com"] }
wallet = "~/.config/solana/id.json"
```

**Comment by armaniferrante** [comment]
> A small proposal for allowing both a custom HTTP JSON-RPC URL and a Websocket URL to be specified in Anchor.toml.
> 
> An example of how it may be specified:
> 
> ```toml
> [provider]
> cluster = { custom = ["https://api.devnet.solana.com", "ws://api.devnet.solana.com"] }
> wallet = "~/.config/solana/id.json"
> ```

I like the idea. What if we did

```toml
[provider]
cluster = { http = "https://api.devnet.solana.com", ws = "ws://api.devnet.solana.com" }
wallet = "~/.config/solana/id.json"
```
